baseurl = "https://boku.dev"
title = "ぼくのBlog"
theme = "hugo-theme-cleanwhite"
languageCode = "ja"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
pagination.pagerSize = 5
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
      header_image = "img/common/home2.JPG"
      SEOTitle = "boku blog"
      description = ""
      keyword = ""
      slogan = ""
      upstreamAttribution = true

      image_404 = "img/common/404_fig.jpg"
      title_404 = "ページがみつかりません :("
      omit_categories = false

      page_view_counter = false
      leancloud_app_id = ""
      leancloud_app_key = ""

      # algolia site search
      algolia_search = true
      algolia_appId = ""
      algolia_indexName = ""
      algolia_apiKey = ""

      # Sidebar settings
      sidebar_about_description = "ハイブリッドロケットやCanSatを作って遊んでました．今はハイブリッドロケットの研究をしてます．キャンプは冬にするものです．"
      sidebar_avatar = "img/common/avatar.jpg"

      featured_tags = true
      featured_condition_size = 1 

      # Baidu Analytics
      ba_track_id = ""

      friends = false
      bookmarks = false
      about_me = true

      # Include any custom CSS and/or JS files, url or relative to /static folder
      custom_css = ["css/custom-font.css"]
      #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

      [params.social]
      rss = true 
      # email = "youremail@gmail.com"
      facebook = "https://www.facebook.com/profile.php?id=100086874489867"
      twitter = "https://x.com/Michiaaaaaa"
      # instagram = "full profile url in instagram"
      github = "https://github.com/MICHI-2"
      
      [[params.friend_link]]
      title = "Linda的博客"
      href =  "https://zhaozhihan.com"

      [[params.bookmark_link]]
      title =  "Martin Fowler"
      href =  "https://martinfowler.com"
      
      # [[params.addtional_menus]]
      # title =  "ARCHIVE"
      # href =  "/archive/"
      # [[params.addtional_menus]]
      # title =  "NOTES"
      # href =  "/notes/"
      [[params.addtional_menus]]
      title =  "ABOUT ME"
      href =  "/about/"

[outputFormats.Algolia]
      baseName = "algolia"
      isPlainText = true
      mediaType = "application/json"
      notAlternative = true

[params.algolia]
      vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
      params = ["categories", "tags"] 

[markup]
      [markup.tableOfContents]
            endLevel = 2
            startLevel = 1
      [markup.highlight]
            style = "dracula"